### ISSUE TITLE
Pilot study release checklist

### ISSUE THREAD

**Issue by saeub** [saeub/okra#18]
All of these *need* to be done before the pilot study:

- [x] Two stages in question answering (only text → rating → text + questions)
- [x] Translate practice indicator
- [x] Don't show ratings for practice tasks
- [x] Better spacing in question answering (and larger hitbox?)
- [x] Display context-aware message after finishing practice task
- [x] Show participant ID in API settings
- [x] Show loading animation while `finishTask` request hasn't finished
- [x] Back button on instructions screen
- [x] Don't enforce portrait mode for reaction time task ~(but lock orientation?)~
- [x] Make emoticon order in ratings configurable
- [x] Use `package_info_plus`
- [x] ~Fix Markdown scrolling performance issues~ → postponed until relevant
- [x] ~Also store task results locally and have some way to access them, just to be safe~ → let's just risk it
